####################################################################
#  Install/Setup OSQuery
####################################################################
- name: Install chocolatey
  win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

- name: Install OSQuery with chocolatey
  win_chocolatey:
    name: osquery
    params: "/InstallService"

- name: Get certificate
  win_template:
    src: conf/agents/certificate.crt
    dest: 'C:\Program Files\osquery\certs\certificate.crt'

- name: Copy OSQuery.flags
  win_template:
    src: conf/agents/osquery.flags
    dest: 'C:\Program Files\osquery\osquery.flags'

- name: Copy OSQuery.key
  win_template:
    src: conf/agents/osquery.key
    dest: 'C:\Program Files\osquery\osquery.key'

- name: Start OSQuery service
  win_service:
    name: osqueryd
    start_mode: auto
    state: restarted