####################################################################
# Install/Setup Nginx
####################################################################
- name: Install/Setup Nginx
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx

- name: Backup NGINX config
  shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- name: Copy Nginx config
  template:
    src: conf/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0600'

- name: Create TLS directory
  file:
    path: /etc/nginx/tls
    owner: root
    group: root
    state: directory
    mode: 0755


- name: Copy Self-signed public cert for Graylog
  template:
    src: 'conf/tls/docker.key'
    dest: '/etc/nginx/tls/graylog.key'
    owner: 'root'
    group: 'root'
    mode: 0400

- name: Copy Self-signed private key for Graylog
  template:
    src: 'conf/tls/docker.crt'
    dest: '/etc/nginx/tls/graylog.crt'
    owner: 'root'
    group: 'root'
    mode: 0400

- name: Copy NGINX config
  template:
    src: conf/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0600'

- name: Copy NGINX config for Graylog
  template:
    src: conf/nginx/ansible_graylog.conf
    dest: /etc/nginx/conf.d/graylog.conf
    owner: root
    group: root
    mode: '0600'

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
    enabled: yes