####################################################################
# Install/Setup Graylog
####################################################################
- name: Download and Install Graylog repo
  apt:
    deb: "{{ graylog_repo_url }}"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install/Setup Graylog
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - graylog-server
    - graylog-enterprise-plugins 
    - graylog-integrations-plugins 
    - graylog-enterprise-integrations-plugins

- name: Covert password to sha256 hash
  shell: "echo -n {{ graylog_admin_password }} | sha256sum | awk '{print $1}'"
  register: pass_contents

- name: Set admin password
  lineinfile:
    path: /etc/graylog/server/server.conf
    regexp: '^root_password_sha2 ='
    line: "root_password_sha2 = {{ pass_contents.stdout }}"

- name: Generate secret key
  shell: "pwgen -s 96 1"
  register: secret_key_content

- name: Set secret key
  shell: sed -i -e "s/password_secret =.*/password_secret = {{ secret_key_content.stdout }}/" /etc/graylog/server/server.conf

- name: Start and Enable Graylog service
  service:
    name: graylog-server.service
    state: restarted
    enabled: yes