####################################################################
# Setup hostname
####################################################################
- name: Set hostname
  hostname:
    name: '{{ kolide_hostname }}.{{ base_domain }}'

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  shell: timedatectl set-ntp on && timedatectl set-timezone {{ timezone }}

####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    
- name: Update all packages to the latest version
  apt:
    upgrade: dist
