####################################################################
# Install/Setup Nginx
####################################################################
- name: Install/Setup Nginx
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx

- name: Backup nginx conf
  shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- name: Create TLS directory for NGINX
  file:
    path: /etc/nginx/tls
    owner: root
    group: root
    state: directory

- name: Copy nginx.conf
  template:
    src: conf/nginx/nginx.conf
    dest:  /etc/nginx/nginx.conf

- name: Copy nginx_kolide.conf
  template:
    src: conf/nginx/ansible_kolide.conf
    dest: /etc/nginx/conf.d/kolide.conf


- name: Copy Self-signed public cert for Graylog
  template:
    src: 'conf/tls/docker.key'
    dest: '/etc/nginx/tls/kolide.key'
    owner: 'root'
    group: 'root'
    mode: 0640

- name: Copy Self-signed private key for Graylog
  template:
    src: 'conf/tls/docker.crt'
    dest: '/etc/nginx/tls/kolide.crt'
    owner: 'root'
    group: 'root'
    mode: 0640

- name: Start Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes