####################################################################
# Install/Setup Filebeat
####################################################################
- name: Add Elastic GPG key
  apt_key:
    url: "{{ elastic_gpg_key_url }}"
    state: present

- name: Add Elastic repo
  apt_repository:
    repo: "{{ elastic_repo_url }}"
    state: present

- name: Install/Setup Filebeat
  package:
    name: "filebeat"
    state: latest

- name: Filebeat.yml config
  template:
    src: 
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600

- name: Start Filebeat service
  service:
    name: filebeat
    state: restarted
    enabled: yes
