####################################################################
# Set hostname
####################################################################
- name: Change the hostname to {{ win_dc_hostname }}
  ansible.windows.win_hostname:
    name: '{{ win_dc_hostname }}' 
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

####################################################################
# Promote Windows Server to Domain controller
####################################################################
- name: Install AD-Domain-Services feature
  win_feature:
    name: 'AD-Domain-Services'
    include_management_tools: True
    include_sub_features: True
    state: present

- name: Promote to domain controller
  ansible.windows.win_domain:
    create_dns_delegation: no
    database_path: C:\Windows\NTDS
    dns_domain_name: '{{ base_domain }}'
    domain_mode: Win2012R2
    #domain_netbios_name: '{{ win_dc_hostname }}' 
    forest_mode: Win2012R2
    safe_mode_password: '{{ ad_safe_mode_password }}'
    sysvol_path: C:\Windows\SYSVOL
  register: domain_install

- name: reboot once DC created
  win_reboot:
  when: domain_install.reboot_required