################################################################################
# Install Elasticsearch
################################################################################
- name: Install Elasticsearch
  apt:
    name: 'elasticsearch={{ elk_version }}'
    
- name: Calculate half the memory of the VM
  debug:
    msg: '{{ ((ansible_memtotal_mb/2000) | round | int)  }}G'

- name: Setting the initial size of the toal heapsize for Elasticsearch
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: '-Xmx{{ ((ansible_memtotal_mb/2000) | round | int)  }}G'

- name: Setting the maximum size of the toal heapsize for Elasticsearch
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: '-Xmx{{ ((ansible_memtotal_mb/2000) | round | int)  }}G'

- name: Restart Elasticsearch
  service:
    name: 'elasticsearch'
    state: 'restarted'
    enabled: yes
